project: test_phageFind
samples_R1: 
          A: Control_T12-1_DC01_R1
          B: Control_T12-2_DC02_R1
          C: Amoxicillin_T12-1_DC13_R1
          D: Amoxicillin_T12-2_DC14_R1
samples_R2: 
          A: Control_T12-1_DC01_R2
          B: Control_T12-2_DC02_R2
          C: Amoxicillin_T12-1_DC13_R1